config/routes.rb
MusicAppScaffold::Application.routes.draw do
  resources :users
  resource :session
  
  resources :tracks, shallow: true
  
  resources :albums do 
    resources :tracks, shallow: true
  end

  #these need to be nested. Look up how.
  resources :bands do 
    resources :albums, only: [:index, :new, :create] 
  end
  
  resources :notes
  
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  album_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  featured   :string(255)      default("REGULAR")
#  lyrics     :text
#

class Track < ActiveRecord::Base
  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
    )
    
  has_one(
    :band,
    class_name: "Band",
    through: :album,
    source: :band
    )
    
  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :track_id,
    primary_key: :id
    )
    
  validates(
    :name,
    :album_id, 
    presence: true
    )
    
  validates(
    :name,
    uniqueness: true
    )
  
  validates(
    :featured,
    inclusion:  %w(REGULAR BONUS)
    )
  def lyric_lines
    lyrics.chomp.split("\r").map { |line| "#{line}" }
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    if @track.try(:save)
      #just @track, not @track_id
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end  
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])

    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])

    if @track.try(:destroy)
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
    end
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :lyrics, :featured)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_track_form.html.erb
<input name="authenticity_token" type="hidden">

<label for="track_name">Track name:</label><br>
<input name="track[name]" type="text" id="track_name" value="<%= @track.name if @track.name %>"></input><br>

<label for="album">Select album:</label><br>
<select name="track[album_id]" id="album">
  <% Album.all.each do |album|%>
    <option value="<%=album.id %>"<%= @track.album == album ? "selected" : "" %>> <%= "#{album.name} - #{album.band.name}" %></option>
  <% end %>
</select></br>

Track Type:<br>
<input type="radio" name="track[featured]" id="featured_track_regular" value="REGULAR"<%= "checked" if @track.featured == "REGULAR" %>>
<label for="featured_track_regular">Studio</label><br>
<input type="radio" name="track[featured]" id="featured_track_bonus" value="BONUS"<%= "checked" if @track.featured == "BONUS" %>>
<label for="featured_track_bonus">Bonus</label><br><br>

<label for="track_lyrics">Lyrics:</label><br>
<textarea name="track[lyrics]" id="track_lyrics"><%= @track.lyrics if @track.lyrics %></textarea><br>

app/views/tracks/edit.html.erb
<h1 style="font-family: sans-serif">edit <%= @track.name %></h1>
  <form action="<%=track_url(@track)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= render partial: 'track_form' %>
  <input type="submit" value="Update"></input>
</form>

app/views/tracks/index.html.erb
<h1>all tracks</h1>

<% Track.all.each do |track| %>
  <%= track.id %>. <b><%= link_to track.name, track_url(track) %></b> - <%=track.album.name %> 
  (<%= track.band.name %>)
  <br>
<%end%>

app/views/tracks/new.html.erb
<h1 style="font-family: sans-serif">add a new track</h1>
<form action="<%= album_tracks_url %>" method="POST">
  <%= render partial: 'track_form' %>

  <input type="submit" value="Create"></input>
</form>

app/views/tracks/show.html.erb
<h1 style="font-family: sans-serif" ><%= @track.name %> </h1>
<h2 style="font-family: sans-serif" >- <%= link_to @track.album.name, album_url(@track.album) %> (<%= link_to @track.band.name, band_url(@track.band) %>) </h2>
<br>
<% if @track.featured == "BONUS" %>
  Bonus track
<%end%><br>

<% if @track.lyrics %>
  <% @track.lyric_lines.each do |line| %>
    <%= line %><br>
  <% end %>
<% end %>

<% if @track.notes %>
  <% @track.notes.all.each do |note| %>
    <%= User.find(note.user_id).email%><br>
    <%= note.body %>
  <%end%>
<%end%>

<%= link_to "Back to #{@track.album.name}", album_url(@track.album) %>
<br>
<%= link_to "More #{@track.band.name}", band_url(@track.band) %>
<br>


<%= link_to "Edit #{@track.name}", edit_track_url %><br>

<%= button_to "Delete track", track_url(@track), method: :delete %>