config/routes.rb
MusicAppScaffold::Application.routes.draw do
  resources :users
  resource :session
  
  resources :tracks, shallow: true
  
  resources :albums do 
    resources :tracks, shallow: true
  end

  #these need to be nested. Look up how.
  resources :bands do 
    resources :albums, only: [:index, :new, :create] 
  end
  
  resources :notes
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password
  before_validation :ensure_session_token
  
  validates(
    :email,
    :password,
    :password_digest,
    :session_token,
    presence: true
    )
    
  validates(
    :email,
    :session_token,
    uniqueness: true
    )
    
  has_many(
    :notes,
    class_name: "Note",
    foreign_key: :user_id,
    primary_key: :id
    )
    
  def password=(plain_text)
      @password = plain_text
      self.password_digest = BCrypt::Password.create(plain_text) 
  end
    
  def self.find_by_credentials(params)
    user = User.find_by_email(params[:email])
    user && user.is_password?(params[:password]) ? user : nil
  end
  
  def self.generate_session_token
    session_token = SecureRandom.hex
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    
    self.session_token
  end

  def is_password?(plain_text)
    BCrypt::Password.new(password_digest).is_password?(plain_text)
  end
  
  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(user_params)
  end

  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
   
   if @user.try(:save)
     login!(@user)
     redirect_to bands_url
   else
     flash.now[:errors] = ["New user NOT created."]
     render :new
   end
  end
end 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>all users</h1>
<ol>
  <% @users.each do |user| %>
    <li> <b><%= link_to user.email, user_url(user) %></b> - <%= user.password%></li>
  <%end%>
</ol>

app/views/users/new.html.erb
<h1 style="font-family: sans-serif">Sign up for finetunes</h1>

<form action="<%= users_url %>" method="POST">
  <input name="authenticity_token" type="hidden">
  
  <label for="new_username">Email</label><br>
  <input name="user[email]" type="text" id="new_email"></input><br>

  <label for="user_password">Password</label><br>
  <input type="password" name="user[password]" id="user_password"><br>

  <button type="submit">Sign Up</button>
  
</form>

app/views/users/show.html.erb
<h1 style="font-family: sans-serif" >Welcome, <%= @user.email %> </h1>