config/routes.rb
MusicAppScaffold::Application.routes.draw do
  resources :users
  resource :session
  
  resources :tracks, shallow: true
  
  resources :albums do 
    resources :tracks, shallow: true
  end

  #these need to be nested. Look up how.
  resources :bands do 
    resources :albums, only: [:index, :new, :create] 
  end
  
  resources :notes
  
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  year       :string(255)
#  band_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  audio      :string(255)
#

class Album < ActiveRecord::Base
  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
    )
    
  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
    )
    
  validates(
    :name,
    :band_id,
    :audio,
    presence: true
    )
  
  validates(
    :name,
    uniqueness: true
    )
    
  validates(
    :audio,
    inclusion:  %w(STUDIO LIVE)
    )
    
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id]) 
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    
    if @album.try(:save)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end  
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end

  def destroy
    @album = Album.find(params[:id])
    
    if @album.try(:destroy)
      redirect_to album_url(@album.band_id)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end
  
  private
  def album_params
    params.require(:album).permit(:name, :band_id, :audio)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_form.html.erb
  <input name="authenticity_token" type="hidden">
  
  <label for="album_name">Album name:</label><br>
  <input type="text" name="album[name]" id="album_name" value="<%= @album.name if @album.name %> "></input><br><br>
  
  
  <label for="band">Select band:</label><br>
  <select name="album[band_id]" id="band">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>" <%= @album.band == band ? "selected" : "" %>>
        <%= band.name %>
      </option>
    <% end %>
  </select><br><br>
  
  
  Type of record:<br>
  <input type="radio" name="album[audio]" id="album_audio_studio" value="STUDIO"<%= "checked" if @album.audio == "STUDIO" %>>
  <label for="album_audio_studio">Studio</label><br>
  <input type="radio" name="album[audio]" id="album_audio_live" value="LIVE"<%= "checked" if @album.audio == "LIVE" %>>
  <label for="album_audio_live">Live</label><br><br>
    


  
  

app/views/albums/edit.html.erb
<h1 style="font-family: sans-serif">edit <%= @album.name %></h1>
  <form action="<%= album_url(@album) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  
  <%= render partial: "album_form"%>
  
  <button type="submit">Update</button>
</form>

app/views/albums/index.html.erb
<h1>all albums</h1>

<% @albums.each do |album| %>
  <%= album.id %>. <b><%= link_to album.name, album_url(album) %></b>  - <%= link_to album.band.name, band_url(album.band.id) %> <br>
  <ul>
    <% album.tracks.each do |track|%>
        <li><%= link_to track.name, track_url(track) %></li>
    <% end %>
  </ul><br>
<%end%>

app/views/albums/new.html.erb
<h1 style="font-family: sans-serif">add a new album</h1>

  <form action="<%= band_albums_url %>" method="POST">

  <%= render partial: "album_form"%>

  <button type="submit">Create</button>
</form>

app/views/albums/show.html.erb
<h1 style="font-family: sans-serif" ><%= @album.name %> </h1>
<h2 style="font-family: sans-serif" >by <%= @album.band.name %> </h1>

<ul>
<% @album.tracks.each do |track| %>
  <li><%= link_to track.name, track_url(track) %></li>
<% end %>
</ul>

<%= "#{@album.audio.capitalize} Album" if @album.audio %><br><br>

<%= link_to "Add a Track to #{@album.name}", new_album_track_url(@album) %><br>

<%= link_to "Add a #{@album.band.name} Album", new_band_album_url(@album.band) %><br>

<%= link_to "Edit #{@album.name}", edit_album_url %><br>

<%= link_to "All albums", albums_url %><br>

<%= button_to "Delete album", album_url(@album), method: :delete %>