config/routes.rb
MusicAppScaffold::Application.routes.draw do
  resources :users
  resource :session
  
  resources :tracks, shallow: true
  
  resources :albums do 
    resources :tracks, shallow: true
  end

  #these need to be nested. Look up how.
  resources :bands do 
    resources :albums, only: [:index, :new, :create] 
  end
  
  resources :notes
  
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
    )
    
  has_many(
    :tracks,
    class_name: "Track",
    through: :albums,
    source: :tracks
    )
    
  validates(
    :name,
    uniqueness: true,
    presence: true
    )
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    
    if @band.try(:save)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end  
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def destroy
    @band = Band.find(params[:id])
    
    if @band.try(:destroy)
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end
  
  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_band_form.html.erb
<% action_url = (verb == "POST" ? bands_url : band_url(params[:id])) %>
<% button_msg = (verb == "POST" ? "Create" : "Update") %>

<form action="<%= action_url %>" method="POST">
  <input name="authenticity_token" type="hidden">
  
  <label for="new_band_name">Name of your band:</label><br>
  <input name="band[name]" type="text" id="new_band_name" value="<%= @band.name %>"></input><br>

  <input type="submit" value="<%= button_msg %>"></input>

app/views/bands/edit.html.erb
<h1 style="font-family: sans-serif">edit <%= @band.name %> </h1>

  <%= render partial: "band_form", locals: {verb: "PATCH"}%>
  <input type="hidden" name="_method" value="PATCH">

app/views/bands/index.html.erb
<h1 style="font-family: sans-serif">all bands</h1>

<% @bands.each do |band| %>
  <%= band.id %>.<b><%= link_to band.name, band_url(band) %></b><br>
  <ul>
    <% band.albums.each do |album|%>
        <li><%= link_to album.name, album_url(album) %></li>
    <% end %>
  </ul><br>
<%end%>

<%= link_to "Create a New Band", new_band_url %>

app/views/bands/new.html.erb
<h1 style="font-family: sans-serif">Save a new band</h1>

<%= render partial: "band_form", locals: { verb: "POST" }%>
  
</form>

app/views/bands/show.html.erb
<h1 style="font-family: sans-serif" ><%= @band.name %>'s albums </h1>

<%@band.albums.each do |album|%>
  <b><%= link_to album.name, album_url(album) %></b>
  <ul>
    <%album.tracks.each do |track|%>
      <li><%= link_to track.name, track_url(track) %></li>
    <% end %>
  </ul>
<%end%><br>


<%= link_to "Add a #{@band.name} Album", new_band_album_url(@band) %>
<br>
<%= link_to "All bands", bands_url %>
<br>

<%= link_to "Edit #{@band.name}", edit_band_url %>
<br>

<%= button_to "Delete band", band_url(@band), method: :delete %>

<!-- <a href="http://cashcats.biz">Cat Pictures</a> -->